[HOPSWORKS-2750] Git logs
logicalclocks/hopslog-chef pull request #68
Opened 2022-01-03 13:27 UTC by gibchikafa

2022-02-23 13:58 UTC, jimdowling reviewed
Is the purpose of this PR to save all the logs from git operations?
I assume yes.

2022-02-23 14:08 UTC, jimdowling requested changes
Tiny fix.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +end
Ok, the other recipes do this. I don't know why, but i guess the operation is idempotent.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +git_owner = ""
Change these lines to 
  git_owner = "glassfish"
  git_group = "glassfish"
  
  Then you can remove the else clause in the statement below.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +  git_owner = "glassfish"
Remove this else clause, see comment above.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +group node['elastic']['user'] do
This should be
node['elastic']['group']
right?

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +  not_if { node['install']['external_users'].casecmp("true") == 0 }
nice. need this.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +end
I trust this works, have no idea.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +logstash_endpoint = "#{logstash_fqdn}:#{node['logstash']['beats']['git_port']}"
looks good.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +end
ok

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +end
ok

2022-02-23 14:08 UTC, jimdowling commented on recipes/_filebeat-git.rb
> +end
All of this is cut-and-paste from the other filebeat services. ok.
At some point we should just have 1 filebeat-service.rb file that is parameterized  by jupyter, git, serving.

2022-02-23 14:08 UTC, jimdowling commented on recipes/_logstash.rb
> +
ok

2022-02-23 14:08 UTC, jimdowling commented on templates/default/consul/logstash-consul.hcl.erb
>      }
ok

2023-05-02 07:40 UTC, gibchikafa commented
Replaced with https://github.com/logicalclocks/hopslog-chef/pull/93

2023-05-02 07:40 UTC, closed without merging