[CLOUD-390] update filebeat to allow rseq
logicalclocks/hopslog-chef pull request #91
Opened 2023-03-03 14:13 UTC by gibchikafa

2023-03-13 23:53 UTC, SirOibaf commented
@gibchikafa - what's the purpose of this PR. The changes should have been done in the docker-repo not here. Can we close this one?

2023-03-14 08:26 UTC, gibchikafa commented
Filebeat service also doesn't start without adding this configuration.

2023-03-14 08:46 UTC, SirOibaf commented
On which version?

2023-03-14 09:02 UTC, gibchikafa commented
on ubuntu22.04. It's either we update filebeat or add that configuration to the current filebeat version.

2023-03-17 14:59 UTC, SirOibaf requested changes

2023-03-17 14:59 UTC, SirOibaf commented on templates/default/filebeat.yml.erb
> +seccomp:
We need to update filebeat.

2023-03-17 15:10 UTC, gibchikafa commented
Yes, I updated yesterday but the binaries were not on master yet on repo.hops.works. I reverted to current version to proceed with the test.

2023-03-18 13:06 UTC, SirOibaf requested changes

2023-03-18 13:06 UTC, SirOibaf commented on attributes/default.rb
> +default['filebeat']['url']                      = "#{node['download_url']}/opensearch/filebeat-#{node['filebeat']['version']}-linux-x86_64.tar.gz"
We need to use the oss version.

2023-03-18 14:45 UTC, SirOibaf approved these changes

2023-03-19 14:10 UTC, merged