[HWORKS-659] Use the tmp_directory attribute
logicalclocks/hopslog-chef pull request #96
Opened 2023-07-19 12:23 UTC by kouzant

https://hopsworks.atlassian.net/browse/HWORKS-659

2023-07-19 21:06 UTC, SirOibaf approved these changes

2023-07-19 21:07 UTC, SirOibaf requested changes
You might want to change this line as well - https://github.com/logicalclocks/hopslog-chef/blob/dac7cb7de0433f145dc33ec6cef6379091965765/attributes/default.rb#L28

2023-07-19 21:08 UTC, SirOibaf commented
And this: https://github.com/logicalclocks/hopslog-chef/blob/91bc7a389f169b0b4bf0b46ccb74fdfab91967b9/attributes/default.rb#L58

2023-07-20 10:32 UTC, kouzant commented
@SirOibaf changed both

2023-07-24 14:52 UTC, SirOibaf approved these changes

2023-07-24 14:52 UTC, merged